[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 35
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
PORT = "3008"
GHL_CLIENT_ID = "68474924a586bce22a6e64f7-mbpkmyu4"
GHL_CLIENT_SECRET = "b5a7a120-7df7-4d23-8796-4863cbd08f94"
GHL_REDIRECT_URI = "https://dir.engageautomations.com/api/oauth/callback"
ALLOWED_ORIGINS = "https://dir.engageautomations.com,https://marketplace.gohighlevel.com"
DATABASE_PATH = "/app/data/oauth_installations_enhanced.db"

[volumes]
data = "/app/data"