[deployment]
deploymentTarget = "autoscale"
run = ["node", "dual-server-startup.js"]
publicVisible = true

[run]
command = "node dual-server-startup.js"

# Force all traffic to Express server
[[deployment.routes]]
source = "/(.*)"
destination = "/$1"
type = "proxy"