[deployment]
deploymentTarget = "autoscale"
build = ["npm", "run", "build"]
run = ["npm", "run", "start"]
publicVisible = true

# Ensure all API routes are handled by Express, not static serving
[[deployment.config]]
name = "api_routing"
value = "express"

# ALL routes go to Express server - no static file serving
[[deployment.routes]]
source = "/(.*)"
destination = "/$1"
type = "proxy"