[deployment]
deploymentTarget = "autoscale"
run = ["npx", "tsx", "server/index.ts"]
publicVisible = true

# Force all traffic to Express server
[[deployment.routes]]
source = "/(.*)"
destination = "/$1"
type = "proxy"