[deployment]
deploymentTarget = "autoscale"
build = ["npm", "run", "build"]
run = ["npm", "run", "start"]
publicVisible = true

# Force all traffic to Express server
[[deployment.routes]]
source = "/(.*)"
destination = "/$1"
type = "proxy"