[deployment]
deploymentTarget = "autoscale"
run = ["node", "run.js"]
publicVisible = true

[run]
run = ["node", "run.js"]

# Force all traffic to Express server
[[deployment.routes]]
source = "/(.*)"
destination = "/$1"
type = "proxy"