[deployment]
deploymentTarget = "autoscale"
run = ["npm", "run", "dev"]
publicVisible = true

[run]
command = "npm run dev"

# Force all traffic to Express server
[[deployment.routes]]
source = "/(.*)"
destination = "/$1"
type = "proxy"