[deployment]
deploymentTarget = "autoscale"
run = ["node", "minimal-server.js"]
publicVisible = true

# Force all traffic to Express server
[[deployment.routes]]
source = "/(.*)"
destination = "/$1"
type = "proxy"