[workflows.dev]
name = "Start application"
author = "replit"
template = "basic"
language = "bash"
runButton = "Open website"

[workflows.dev.deployment]
run = ["node", "web-server.js"]
deploymentTarget = "cloudrun"