[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "oauth-backend"

[services.build]
builder = "NIXPACKS"

[services.deploy]
healthcheckPath = "/health"
startCommand = "node index.js"
